### ISSUE TITLE
Modify existing routes to respond with necessary files instead of web pages

### ISSUE THREAD

**Issue by phillipbruce1** [cs481-ekh/f22-softskills#232]
Definition of done:
- [x] #274
- [x] #275
- [x] #276
- [x] #277

**Comment by bsu-jacksonmorton** [comment]
Spent a few hours ~7am-12pm chasing my tail and trying to debug misc behaviors that I came across while implementing some changes to the routes. The logic is essentially there for #274 but for some reason the db is saying that the files are not there when querying for them. I think it has something to do with the URLSearchParams encoding vs the query string encoding for the db and I'm probably just doing something dumb. I'll investigate later tonight if I get the chance.

**Comment by bsu-jacksonmorton** [comment]
#274 should be good to go. The error mentioned previously has been resolved and turned out to be a side effect of some db code.

**Comment by bsu-jacksonmorton** [comment]
Spent 3 hours working on addPermission route changes and debugging associated errors

**Comment by bsu-jacksonmorton** [comment]
Spent ~90 minutes this morning finishing up the final task for this story (#277) and doing some bug investigating.
